#!/usr/bin/env python3
"""
Create yet another little script.

Usage: {script} [options] DESC

Arguments:
    DESC - Description of the script.
           What does it do?

Options:
    -h, --help
        Show this screen and exit.

    --verbose
        Raise verbosity level.
"""

import sys
from contextlib import suppress
from os import environ, system
from pathlib import Path
from subprocess import run

SCRIPT_TEMPLATE = "script-templates/process_text_files_using_python.py"


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    setattr(debug, "enabled", args["--verbose"])
    debug(f"Running with arguments {dict(args)!r}")
    projects = Path(environ["GIT_PROJECTS_DIR"] or "~/Documents/Projects").resolve()
    name = "-".join(args["DESC"].split()).lower()
    debug(f"script-name: {name}")
    path = projects.joinpath("small_scripts").joinpath(name)
    if path.exists():
        print("ERROR: Script with this name already exists!", file=sys.stderr)
        exit(1)
    debug(f"script-path: {path}")
    script = Path(__file__).parent.joinpath(SCRIPT_TEMPLATE).read_text()
    path.write_text("")
    path.chmod(path.stat().st_mode | 0o100)
    path.write_text(script.replace("SCRIPT_DESCRIPTION", args["DESC"] + "."))
    run(["nvim", "--", str(path)])
    system("$SHELL")


def debug(msg: str):
    if getattr(debug, "enabled", False):
        print(msg)


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(*sys.argv)
