#!/usr/bin/env python3
"""
Yet another script of mine.
Get maximum achievable steam level using provided amount of XP.

Usage: {script} [options] XP

Arguments:
    XP - amount of XP of Steam account

Options:
    -h, --help
        Show this screen and exit.
"""

import sys
from contextlib import suppress
from pathlib import Path


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    xp = int(eval(args["XP"]))
    level = 0
    required_xp_for_next_level = 100
    while xp >= required_xp_for_next_level:
        xp -= required_xp_for_next_level
        level += 1
        if level % 10 == 0:
            required_xp_for_next_level += 100
    print(f"Level: {level}")
    print(f"{required_xp_for_next_level - xp} XP to reach Level {level + 1}")


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
