#!/usr/bin/env python3
"""
Yet another script of mine.

Usage: {script} [options]

Options:
    -h, --help
        Show this screen and exit.
"""

import sys
from contextlib import suppress
from pathlib import Path

from PIL import ImageGrab


def get_pixel_height(image, tolerance: int = 0) -> int:
    w, h = image.size
    pixels = image.load()
    deltas = set()
    for x in range(w):
        old_pixel = pixels[x, 0]
        for y in range(1, h):
            pixel = pixels[x, y]
            if any(abs(x - y) > tolerance for x, y in zip(pixel, old_pixel)):
                deltas.add(y)
            old_pixel = pixel
    diffs = [y - x for x, y in windows(sorted(deltas))]
    if min(diffs) == 1 and h > 64 and tolerance < 32:
        return get_pixel_height(image, max(tolerance, 1) * 2)
    return sum(dy // min(diffs) for dy in diffs)


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    img = ImageGrab.grabclipboard().convert("RGBA")
    print(get_pixel_height(img))


def windows(xs, n: int = 2):
    xs = iter(xs)
    x1 = next(xs)
    for x2 in xs:
        yield x1, x2
        x1 = x2


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
