#!/bin/sh -e

git log --format='%aN' | sort -u | while read -r name; do
	printf "%s\t" "$name"
	git log --author="$name" --pretty=tformat: --numstat | awk '{
		add += $1;
		subs += $2;
		loc += $1 - $2
	} END {
		printf "added lines: %s, removed lines: %s, total lines: %s\n",
		add, subs, loc
	}' -
done
