#!/usr/bin/env python3
"""
Print how to do something.

Usage: {script} [options] DESIRE

Arguments:
    DESIRE - What you want to do.

Options:
    -h, --help
        Show this screen and exit.
"""

import contextlib
import subprocess
import sys
from base64 import b64encode
from contextlib import suppress
from difflib import get_close_matches
from pathlib import Path
from subprocess import PIPE, run
from itertools import chain

knowledge = {
    "Factorio": {
        "increase inventory size of player": (
            "/c game.player.force.character_inventory_slots_bonus=90",
            lambda cmd: type(cmd),
        )
    }
}


def main(script_name: str, *script_args: str):
    docstring = __doc__.format(script=Path(script_name).name)
    if script_args and script_args[0] in ("-h", "--help"):
        print(docstring)
        exit(0)
    if not script_args:
        print("Invalid usage", file=sys.stderr)
        exit(1)
    request = " ".join(script_args)
    win = run(["xdotool", "getactivewindow", "getwindowname"], stdout=PIPE).stdout
    context = win.decode("utf-8", "ignore").split()[0].split(":")[0]
    matches = list(get_close_matches(request, knowledge[context], n=1))
    if not matches:
        print("idk", file=sys.stderr)
        exit(1)
    answer, action = knowledge[context][matches[0]]
    print(answer)
    action(answer)
    # copy_to_clipboard(answer)


def press_keys(*keys: str):
    run(["xdotool"] + list(chain(*(["key", key] for key in keys))))


def type(message: str):
    run(["xdotool", "type", message])


def copy_to_clipboard(message: str, stdout=sys.stdout):
    with contextlib.suppress(ImportError):
        table = __import__("pandas").DataFrame([message])
        table.to_clipboard(excel=False, index=False, header=False)
        return
    with contextlib.suppress(OSError):
        cmd = ["/usr/bin/xsel", "-ib"]
        subprocess.run(cmd, check=True, input=message.encode("utf-8"))
        return
    if stdout.isatty():
        encoded = b64encode(message.encode("utf-8")).decode("ascii")
        print(f"\x1b]52;c;{encoded}\x07", file=stdout)
    print("Copy this:\n" + message, file=stdout)


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
