#!/bin/sh

{
	window=$WINDOWID
	# TODO: fallback to activewindow
	# window=$(xdotool getactivewindow)
	width=$(xdotool getwindowgeometry --shell "$window" | sed -n 4p | cut -d= -f2)
	height=$(xdotool getwindowgeometry --shell "$window" | sed -n 5p | cut -d= -f2)
	# { columns: 128, rows: 36 } -> { width: 1026, height: 506 }
	# w = 8 * cols + 2
	# h = 14 * rows + 2
	w=$(((width - 2) / 8 * 8 + 2))
	h=$(((height - 2) / 14 * 14 + 2))
	for _ in $(seq 16); do
		sleep 0.015625
		# echo "window_id = $window"
		# echo "width:  $width -> $w"
		# echo "height: $height -> $h"
		xdotool windowsize "$window" $w $h
	done
}&

if [ -z "$1" ]; then
	$SHELL
else
	"$@"
fi
