#!/usr/bin/env python3
"""
Filter png image.

Usage: {script} SPEED

Arguments:
    SPEED - Desired speed of time

"""

import sys
from contextlib import suppress
from pathlib import Path
import time

UPS = 128


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    speed = float(args["SPEED"])
    clock_id = time.CLOCK_REALTIME
    t1 = time.clock_gettime(clock_id)
    while True:
        time.sleep(1 / UPS)
        t0, t1 = t1, time.clock_gettime(clock_id)
        dt = t1 - t0
        t1 = t0 + dt * speed
        # print(f"{t0 = }\n{t1 = }\n{dt = }\n")
        time.clock_settime(clock_id, t1)


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
