#!/usr/bin/env python3

import contextlib
import os
import select
import sys
from math import gcd

try:
    import termios
except ModuleNotFoundError:
    termios = None


def get_background_color(timeout=0.1, default_color=None):
    if not termios:
        return default_color
    stdin_fd = sys.stdin.fileno()
    prev_flags = termios.tcgetattr(stdin_fd)
    flags = prev_flags.copy()
    flags[3] &= ~termios.ICANON & ~termios.ECHO
    termios.tcsetattr(stdin_fd, termios.TCSANOW, flags)
    sys.stdout.write("\x1b]11;?\x07")
    sys.stdout.flush()
    if select.select([sys.stdin], [], [], timeout)[0] != [sys.stdin]:
        termios.tcsetattr(stdin_fd, termios.TCSADRAIN, prev_flags)
        return default_color
    color = os.read(stdin_fd, 24)[9:23]
    termios.tcsetattr(stdin_fd, termios.TCSADRAIN, prev_flags)
    with contextlib.suppress(ValueError):
        color = tuple(int(color, 16) for color in color.decode().split("/"))
        if len(color) == 3 and all(0 <= x <= 65535 for x in color):
            return color
    return default_color


width, height = os.get_terminal_size()
scale = gcd(width, height * 2)
print("Terminal size:")
print(f"  width  = {width} chars = {width} squares")
print(f"  height = {height:3} chars = {height * 2} squares")
print(f"aspect ratio = {width // scale} × {height * 2 // scale}")
print(f"width / height = {width / height / 2}")
w16x9 = min(width // 16, 2 * height // 9)
print(f"16×9 subwindow = {16 * w16x9} × {9 * w16x9}")
if color := get_background_color(timeout=0.1):
    red, green, blue = color
    print("Current background color:")
    print(f"  red   = {red / 65535:.5f} ≈ {red // 256:3} / 255")
    print(f"  green = {green / 65535:.5f} ≈ {green // 256:3} / 255")
    print(f"  blue  = {blue / 65535:.5f} ≈ {blue // 256:3} / 255")
else:
    print("P.S. Fail to get background color!")
