#!/usr/bin/env python3
"""
Yet another script of mine.

Usage: {script} [options] [PATH]

Arguments:
    PATH - Path to the file or directory with files.
           If not specified, use current directory.

Options:
    -h, --help
        Show this screen and exit.

    --verbose
        Raise verbosity level.
"""

import sys
from contextlib import suppress
from pathlib import Path


def process(path: Path):
    text = path.read_text()
    lines = text.splitlines()
    print("\n\n//", path, end="\n\n")
    for line in lines:
        print(line.replace("\t", " " * 4))


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    setattr(debug, "enabled", args["--verbose"])
    debug(f"Running with arguments {dict(args)!r}")
    paths = [Path(args["PATH"] or ".")]
    for path in paths:
        if path.is_dir():
            paths.extend(path.joinpath(f) for f in path.iterdir())
        elif path.is_file():
            debug(f"Processing {path}")
            try:
                process(path)
            except UnicodeDecodeError:
                debug(f"  Failure: {path} is binary file")


def debug(*objects: object, sep: str = " "):
    if getattr(debug, "enabled", False):
        print(sep.join(map(str, objects)))


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
