#!/usr/bin/env python3
"""
Count seconds since start of program.

Usage: {script} [options]

Options:
    -h, --help
        Show this screen and exit.
"""

import sys
from contextlib import suppress
from pathlib import Path
from time import monotonic as get_time


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    __import__("docopt").docopt(doc, script_args)
    print("...", end="")
    t0 = get_time()
    with suppress(KeyboardInterrupt):
        while True:
            dt = get_time() - t0
            print(f"\r {dt:6.3f} ", end="")


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
