#!/usr/bin/env python3
"""
Yet another script of mine.

Usage: {script} [options]

Options:
    -h, --help
        Show this screen and exit.
"""

from itertools import zip_longest
import sys
from contextlib import suppress
from pathlib import Path


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    rows = [line.split() for line in sys.stdin.readlines()]
    lens = [max(map(len, row)) for row in rows]
    for row in transpose(rows):
        line = " ".join((x or " ").center(lens[i]) for i, x in enumerate(row))
        print(line.rstrip())


def transpose(matrix: list[list]) -> list[list]:
    return list(map(list, zip_longest(*matrix, fillvalue=None)))


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
