#!/usr/bin/env python3
import openpyxl
from pathlib import Path
import sys


def main(tsv_path: Path, xlsx_path: Path | None = None):
    if xlsx_path is None:
        xlsx_path = tsv_path.with_suffix(".xlsx")
    if xlsx_path.exists():
        wb = openpyxl.open(xlsx_path)
        sheet = wb.active
    else:
        title = " ".join(x.capitalize() for x in tsv_path.stem.replace("-", " ").split())
        wb = openpyxl.Workbook()
        sheet = wb.active
        sheet.title = title or "Sheet1"
    lines = tsv_path.read_text(encoding="utf-8").splitlines()
    rows = [list(map(tsv_unescape, line.split("\t"))) for line in lines]
    for i, row in enumerate(rows):
        for j, value in enumerate(row):
            old_value = sheet.cell(i + 1, j + 1).value
            if value == "" if old_value is None else str(old_value):
                continue
            print(old_value, "->", value)
            sheet.cell(i + 1, j + 1).value = value
            # if j and value and value == row[j - 1]:
            #     sheet.merge_cells(None, i + 1, j, i + 1, j + 1)
            # if i and value and value == rows[i - 1][j]:
            #     sheet.merge_cells(None, i, j + 1, i + 1, j + 1)
    wb.save(xlsx_path)


ESCAPE_SEQUENCES: dict[str, str] = {"\t": r"\t", "\n": r"\n", "\r": r"\r", "\\": r"\\"}
UNESCAPE = {seq[1]: char for char, seq in ESCAPE_SEQUENCES.items()}


def tsv_escape(obj: object) -> str:
    if obj is None:
        return ""
    return "".join(ESCAPE_SEQUENCES.get(ch, ch) for ch in str(obj))


def tsv_unescape(escaped_string: str) -> str:
    chars = iter(escaped_string)
    return "".join(UNESCAPE[next(chars)] if ch == "\\" else ch for ch in chars)


def test_escape():
    escaped = tsv_escape("lkjasdfo\rkldsfja\n23 jfsdaf\\lksdjf\tdklsfj \r\n")
    expected = r"lkjasdfo\rkldsfja\n23 jfsdaf\\lksdjf\tdklsfj \r\n"
    assert expected == escaped


def test_unescape():
    string = "lkjasdfo\rkldsfja\n23 jfsdaf\\lksdjf\tdklsfj \r\n"
    escaped = tsv_escape(string)
    assert string == tsv_unescape(escaped)


if __name__ == "__main__":
    main(*map(Path, sys.argv[1:]))
